### ISSUE TITLE
missing file heap_bit_searcher.h

### ISSUE THREAD

**Issue by taburete** [nicknash/integer-structures#1]
The header file heap_bit_searcher.h is missing.

**Comment by nicknash** [comment]
Thanks for pointing this out! I'll sort it out this evening.

**Comment by nicknash** [comment]
heap_bit_searcher.h seems to be there after all - what's the compilation error you are seeing?

**Comment by taburete** [comment]
What it is missing is linear_bit_searcher.h Sorry for the mistake. The
compilation error is

g++ -c -Wall -O3 -I../   ../xor_gens/xor_gens.cpp
g++ -Wall -O3 -I../   perf_test.cpp -o perf_test timer.o xor_gens.o
In file included from ../lpctrie/lpctrie.h:10:0,
                 from ../qtrie/lpcqtrie.h:5,
                 from perf_test.cpp:9:
../node_structs/node_structs.h:5:46: fatal error:
node_structs/linear_bit_searcher.h: No such file or directory
compilation terminated.
make: *** [perf_test] Error 1


2017-06-08 22:23 GMT+02:00 Nick <notifications@github.com>:

**Comment by nicknash** [comment]
Hi - sorry for the delay sorting this - I've tracked down what I think is the original code. I also removed some object files that were accidentally checked in, as they confused the build until I ran "make clean".

All the code in this repo now builds fine for me. Hope that helps!
