### ISSUE TITLE
LPC Burst Trie reports wrong predecessors

### ISSUE THREAD

**Issue by pdinklag** [nicknash/integer-structures#2]
I am currently studying dynamic predecessor data structures and am also considering your 2008 WEA paper, where your main result is the LPC Burst Trie that practically "won" your evaluation by using the least memory and being the fastest on all noteworthy instances. I'd thus like to include it in my benchmark.

However, I am having trouble getting it to work properly. I figured out that the `locate` operation computes the predecessor (even though the paper describes it as successor). A good number of queries yield wrong results. The following program is the smallest example I could find to demonstrate.

The keys are an excerpt from my benchmark, which, in this case, feeds uniformly random 32-bit integers to the data structures. Then, it performs predecessor queries on more random keys. To verify the results, I also implemented a very naive but correct predecessor search ( `locate_naively`).

```.cpp
#include <cstdint>
#include <iostream>
#include <vector>

#include <btrie/lpcbtrie.h>

using int_t = uint32_t;

// naive predecessor search
const int_t* locate_naively(const std::vector<int_t>& keys, const int_t x) {
    const int_t* predecessor = nullptr;
    for(const int_t& key : keys) {
        if(key <= x && (!predecessor || key > *predecessor)) {
            predecessor = &key;
        }
    }
    return predecessor;
}

// inserted keys
std::vector<int_t> keys = {
    2047777281,
    1142097108,
    1243693029,
    606040460,
};

// keys to query
std::vector<int_t> queries = {
    1125126659,
    1958119416,
    2021405905,
};

int main(int argc, char** argv) {
    // initialize and insert keys
    LPCBTrie<int_t, int_t> trie;
    for(auto x : keys) {
        trie.insert(x, x);
    }
    
    // perform queries
    for(auto x : queries) {
        std::cout << "locate(" << x << ") = ";
        const auto* y = trie.locate(x);
        if(y) std::cout << *y; else std::cout << "NIL";

        // verify
        const auto* correct = locate_naively(keys, x);
        if((y && !correct) || (!y && correct) || (y && correct && *y != *correct)) {
            std::cout << " (WRONG, should be ";
            if(correct) std::cout << *correct; else std::cout << "NIL";
            std::cout << ")";
        }
        
        std::cout << std::endl;
    }
}
```

Executing the above produces the following output:
```
locate(1125126659) = 0 (WRONG, should be 606040460)
locate(1958119416) = 1142097108 (WRONG, should be 1243693029)
locate(2021405905) = 1142097108 (WRONG, should be 1243693029)
```

Double-checking manually, the reported predecessors are indeed wrong. The fact that zero is returned by the first query is especially awkward, because zero was never added to the trie.

Note that this is merely a small example. In larger instances, out of ten million queries, nearly one million gives me wrong results for pretty much any random seed or universe (e.g., also, 64-bit integers). I could not identify why this happens and on all instances with small, human-readable keys it appears to work just fine. Therefore I am opening this issue.

Is this issue known? May I be running into some edge case that is not covered by your implementation, or is there generally something wrong with the way I use the data structure, e.g. any pre-assumptions I am violating?
Thank you for your time!

**Comment by pdinklag** [comment]
Our research assistant has fixed this problem and gave a pull request in #3 .

**Comment by nicknash** [comment]
@pdinklag @herlez Thank you both so much for this. Congratulations on your paper.
